title: Hakuna Matata
description: I thought Why I shouldn't give it up a try

url: https://someshbose.in
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

exclude: ['vendor']
navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter:
   facebook:
   email:

google_analytics:
